"""empty message

Revision ID: 46726050db10
Revises: 
Create Date: 2020-08-21 15:33:31.326130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46726050db10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('slot_1', sa.String(), nullable=False),
    sa.Column('slot_2', sa.String(), nullable=False),
    sa.Column('slot_3', sa.String(), nullable=False),
    sa.Column('slot_4', sa.String(), nullable=False),
    sa.Column('slot_5', sa.String(), nullable=False),
    sa.Column('slot_6', sa.String(), nullable=False),
    sa.Column('trainerClass', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('pre_battle_quote', sa.Text(), nullable=False),
    sa.Column('post_battle_quote', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainers')
    # ### end Alembic commands ###
