"""empty message

Revision ID: b4aa001822f7
Revises: 46726050db10
Create Date: 2020-09-22 11:37:25.524666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aa001822f7'
down_revision = '46726050db10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dateObtainBoulderBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('dateObtainCascadeBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('dateObtainEarthBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('dateObtainMarshBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('dateObtainRainbowBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('dateObtainSoulBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('dateObtainThunderBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('dateObtainVolcanoBadge', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('teamObtainBoulderBadge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teamObtainCascadeBadge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teamObtainEarthBadge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teamObtainMarshBadge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teamObtainRainbowBadge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teamObtainSoulBadge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teamObtainThunderBadge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teamObtainVolcanoBadge', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'teamObtainVolcanoBadge')
    op.drop_column('users', 'teamObtainThunderBadge')
    op.drop_column('users', 'teamObtainSoulBadge')
    op.drop_column('users', 'teamObtainRainbowBadge')
    op.drop_column('users', 'teamObtainMarshBadge')
    op.drop_column('users', 'teamObtainEarthBadge')
    op.drop_column('users', 'teamObtainCascadeBadge')
    op.drop_column('users', 'teamObtainBoulderBadge')
    op.drop_column('users', 'dateObtainVolcanoBadge')
    op.drop_column('users', 'dateObtainThunderBadge')
    op.drop_column('users', 'dateObtainSoulBadge')
    op.drop_column('users', 'dateObtainRainbowBadge')
    op.drop_column('users', 'dateObtainMarshBadge')
    op.drop_column('users', 'dateObtainEarthBadge')
    op.drop_column('users', 'dateObtainCascadeBadge')
    op.drop_column('users', 'dateObtainBoulderBadge')
    # ### end Alembic commands ###
